# Generated by Django 5.2.9 on 2026-01-05 16:54

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('is_published', models.BooleanField(default=True, verbose_name='Publish')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('img', models.ImageField(upload_to='blog/posts/', verbose_name='image')),
                ('content', tinymce.models.HTMLField(default='Add some content here')),
                ('author', models.CharField(default='Надежда', verbose_name='Author')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publish')),
                ('tag', models.ManyToManyField(related_name='posts', to='blog.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
