# Generated by Django 5.2.9 on 2026-02-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('star', models.FloatField(default=5.0, verbose_name='Оценка')),
                ('aim', models.CharField(max_length=150, verbose_name='Цель занятий')),
                ('review', models.TextField(verbose_name='Текст отзыва')),
                ('date', models.DateField(verbose_name='Дата публикации отзыва')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовать')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
